### ISSUE TITLE
Search hotkey

### ISSUE THREAD

**Issue by Eomm** [fastify/website#103]
I was looking to turn on the hotkey: 

<img width="187" alt="image" src="https://github.com/fastify/website-next/assets/11404065/d6df48ae-8933-46f1-8bf9-b8dda453800e">

Would you happen to know how?
(in case we may open a new dedicated issue)

_Originally posted by @Eomm in https://github.com/fastify/website-next/pull/102#discussion_r1225194795_

**Comment by ShogunPanda** [comment]
Yup, it's on my TODO list for this evening.
