### ISSUE TITLE
Search does not point to the linked anchor

### ISSUE THREAD

**Issue by mcollina** [fastify/website#136]
If you try to search for "listen" in the website and click on the second result (`server.listen()`), the page that will load would have the anchor set, so it would not scroll down.

cc @ShogunPanda

**Comment by ShogunPanda** [comment]
Once https://github.com/oramasearch/orama/pull/463 lands and it's released on NPM, we can fix this by bumping the dependency.

**Comment by micheleriva** [comment]
Will release this within this week with `v1.2.1`

**Comment by mcollina** [comment]
thx!

**Comment by micheleriva** [comment]
@mcollina @ShogunPanda FYI Orama `v1.2.1` just got released with this fix

**Comment by Eomm** [comment]
bumping 👍🏼
