### ISSUE TITLE
Upgrade to docusaurus v3

### ISSUE THREAD

**Issue by Eomm** [fastify/website#212]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

As titled:

- https://github.com/facebook/docusaurus/releases/tag/v3.0.0
- docs: https://docusaurus.io/docs/migration/v3

### Motivation

We need to test the redirects mainly.

### Example

-

**Comment by james-kaguru** [comment]
@Eomm id like to help out with this issue. I see that Docusaurus required us to update several packages as well as some parts of the code. Should I do it all in one PR or break the updates into several PRs?

**Comment by mcollina** [comment]
one PR would be best

**Comment by james-kaguru** [comment]
Well noted @mcollina

**Comment by james-kaguru** [comment]
Ive seen that one of the files(docx/Reference/TypeScript.md) in the fastify/fastify repo requires an update in order for the project to build. This was identified by running 

```
npx docusaurus-mdx-checker
```
The command helps with checking for changes that require updates for v3. I will proceed to create a  pull request for that.Then come back to address the changes on fastify/website repo.
