### ISSUE TITLE
Use `download-tartifact@v3.0` when (and if) is released

### ISSUE THREAD

**Issue by Gesma94** [fastify/website#213]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

After we faced some problems in issue https://github.com/fastify/website/issues/176#issuecomment-2072564361, we stopped using `download-tartifact@v2.0` because it's not compatible with `upload-artifact@v4.0`.

We opened a PR in `download-artifact` repo https://github.com/alehechka/download-tartifact/pull/2, and it might be good to go back using `download-tartifact` once a new version is released.

**Comment by Eomm** [comment]
The external repo did not reply - I think we are good with the current setup
