### ISSUE TITLE
Development server is not starting

### ISSUE THREAD

**Issue by james-kaguru** [fastify/website#217]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.0.0

### Plugin version

n/a

### Node.js version

20.11.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

Ventura 13.6.6

### Description

I have just downloaded the fastify website and proceeded to start the dev server following the instruction in the README.md but I got an error as shown below.

<img width="1580" alt="Screenshot 2024-05-02 at 4 03 45 PM" src="https://github.com/fastify/website/assets/47499826/7e390961-04a7-4502-8d4d-375eacebbd87">

### Link to code that reproduces the bug

n/a

### Expected Behavior

for the dev server to start correctly

**Comment by mcollina** [comment]
cc @Eomm

**Comment by Eomm** [comment]
Could you list the commands?

I think it misses one

**Comment by james-kaguru** [comment]
@Eomm  Here are the commands

```
npm install
npm --prefix ./scripts install
npm start

```

**Comment by Eomm** [comment]
Run npm run build:website too

**Comment by james-kaguru** [comment]
@Eomm Im getting an error that occurs when the build:website is run particularly from /scripts/download-release.sh . Is says 

"No release found. Did you run gh auth login?"

**Comment by james-kaguru** [comment]
@Eomm I was able to solve the issue by installing the github cli.. I could help with the update of the README.md to ensure new developers will be able to setup correctly.  However now that the dev server is running, Im not able to find where the code for the docs are. Could you kindly help me oout with this

**Comment by Eomm** [comment]
It is explained in the "build" section https://github.com/fastify/website

The documentation lives in the main fastify repository: fastify/fastify/docs

Feel free to improve the wording if it is not clear

**Comment by james-kaguru** [comment]
thanks @Eomm  for the clarificatioon..honestly I hadnt read that. I think rearragning the order might help with that. Ill proceed to create a PR for that
