### ISSUE TITLE
Error page is gone, redirected from the site

### ISSUE THREAD

**Issue by scarletquasar** [fastify/website#229]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

-

### Plugin version

-

### Node.js version

-

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

-

### Description

https://github.com/fastify/fastify/blob/main/docs/Server.md#seterrorhandler
https://fastify.dev/docs/v1.14.x/Documentation/Error-Handling/

**Comment by Eomm** [comment]
<img width="1002" alt="image" src="https://github.com/user-attachments/assets/48c055e5-0497-48ee-a30f-f8051a994fe4">

**Comment by scarletquasar** [comment]
> <img alt="image" width="1002" src="https://private-user-images.githubusercontent.com/11404065/391231448-48c055e5-0497-48ee-a30f-f8051a994fe4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwNzQ5NjAsIm5iZiI6MTczMzA3NDY2MCwicGF0aCI6Ii8xMTQwNDA2NS8zOTEyMzE0NDgtNDhjMDU1ZTUtMDQ5Ny00OGVlLWEzMGYtZjgwNTFhOTk0ZmU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAxVDE3Mzc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2ZGQ4ZDE1MWQyYWJjN2I5MTZiMzdmMjgwMzMyODI2MmIyNzgyYjE0M2FhN2U3M2M2MmFmNGVlMDMzYWE3MjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-9lqiRe2EPPP7f9X7vuIv6S5cp7def2pNtfn80VfQQY">

Just then the SEO needs to be fixed, since google results redirect to that version documentation

**Comment by Eomm** [comment]
If you know what it should be done, could you drop a message here?

https://github.com/fastify/website/issues/29
