### ISSUE TITLE
Remove the organization section

### ISSUE THREAD

**Issue by Eomm** [fastify/website#255]
As decision from an [internal discussion](https://github.com/orgs/fastify/discussions/48), the fastify maintainers do agree to do the following:

```[tasklist]
### Tasks
- [ ] Remove the `using` section from the homepage
- [ ] Remove from the [org page](https://fastify.dev/organisations/) all the companies that are not sponsor or are not affiliated to any fastify's maintainers (regardless the team)
```

## Task 1

This `Using` section and keep the `Sponsors` only:

<img width="1397" alt="image" src="https://github.com/user-attachments/assets/4817822e-5924-496b-bae8-4648ea6a78d2">

Add anyway the link to the `https://fastify.dev/organisations/` page.

## Task 2

The page https://fastify.dev/organisations/ should be cleaned by external orgs.
We must replace the `How to be featured here` section with a call to action to the sponsor page:
https://github.com/sponsors/fastify

**Comment by Uzlopak** [comment]
Do we have a contact to mercedes benz? I think that logo was scraped from github org of mercedez benz?

I found a svg of the logo long time ago. should look better, imho.

https://github.com/fastify/website/blob/91145fb3be0bff9f0d9ddbbd21bf4f3b8173da3e/static/img/organisations/mercedes-benz.svg

**Comment by Eomm** [comment]
> Do we have a contact to mercedes benz?

No

> I think that logo was scraped from github org of mercedez benz?

Yes, TBH I regret that and if the sponsor does not open a PR, I would leave it behind..

**Comment by jsumners** [comment]
> Yes, TBH I regret that and if the sponsor does not open a PR, I would leave it behind..

Agree
