### ISSUE TITLE
bug: wrong plugin name

### ISSUE THREAD

**Issue by Eomm** [fastify/website#81]
at https://fastify.github.io/website-next/ecosystem

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/11404065/231491410-c4298ad2-8015-4bed-b80a-c028e20cb4cc.png">

**Comment by bortolottidev** [comment]
It's a fast fix, there's only a missing space in the ecosystem script. 
Are the script supposed to be covered by test?

**Comment by Eomm** [comment]
> Are the script supposed to be covered by test?

Nope - at this stage we don't have test.
We check the website output only 👍🏼

**Comment by tanvirraj** [comment]
@Eomm, i don't find any `plugins.json` in main branch, am i missing something ?

**Comment by Eomm** [comment]
It is generated by https://github.com/fastify/website-next/blob/main/scripts/build-plugin-list.js when you run `npm run build:website`

**Comment by brandon-charest** [comment]
is anyone actively working on this? If not I can
